version: "3.8"
services:
  node:
    image: node:20
    restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./server/:/home/node/app:rw
    ports:
      - 8081:8081
    command: bash -c "npm install && npm run dev"
    networks:
      - mosquitto_ntw
    depends_on:
      - mosquitto


  mosquitto:
    image: iegomez/mosquitto-go-auth:2.1.0-mosquitto_2.0.15
    restart: always
    command: /usr/sbin/mosquitto -c /etc/mosquitto/config/mosquitto.conf -v
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/etc/mosquitto/config:rw
      - ./mosquitto/conf.d:/etc/mosquitto/conf.d:rw
      - ./mosquitto/data:/etc/mosquitto/data:rw
      - ./mosquitto/log:/etc/mosquitto/log:rw
    networks:
      - mosquitto_ntw


networks:
    mosquitto_ntw:
        driver: bridge