version: "3.8"
services:
  node:
    image: node:20
    restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./server/:/home/node/app:rw
    ports:
      - 8081:8081
    command: bash -c "npm install && npm run dev"
    links:
      - mongo

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/data:/home/data/db:rw
    ports:
      - 27017:27017
  
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/
    ports:
      - 8082:8081

  mosquitto:
    image: iegomez/mosquitto-go-auth:2.1.0-mosquitto_1.6.14
    restart: always
    command: /usr/sbin/mosquitto -c /etc/mosquitto/config/mosquitto.conf -v
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/etc/mosquitto/config:rw
      - ./mosquitto/data:/etc/mosquitto/data:rw
      - ./mosquitto/log:/etc/mosquitto/log:rw

  
volumes:
  mongo-data: 
    driver: local
    