//get all channels
###
GET http://localhost:8081/api/channels HTTP/1.1
Content-Type: application/json
Authorization: r1uh2ra3jc1wnd4e5vds8xaa2gze6f


//get channel by channelId
###
GET http://localhost:8081/api/channels/ch-578f87bc-ca44-4986-8a09-3e6fed838c8e HTTP/1.1
Content-Type: application/json
Authorization: r1uh2ra3jc1wnd4e5vds8xaa2gze6f

//get my channels
###
GET http://localhost:8081/api/users/6553189d968addf9f6ac1732/channels HTTP/1.1
Content-Type: application/json
Authorization: 1jq7lc8yyhhrtg1kwu80s2hto7i4pj

//create channel
###
POST http://localhost:8081/api/channels HTTP/1.1
Content-Type: application/json
Authorization: 5e9kuozbeogpp99z6zdxozrny4m3jx

{
    "name": "channel broker",
    "description": "Es un canal de prueba para el broker",
    "project":"proyecto 2024",
    "ubication":{
        "latitude": 1.0,
        "longitude": 1.0
    },
    "owner":"655e917d013227739e1b46bd"
}

//update channel
###
PUT http://localhost:8081/api/channels/ch-9dcdbaca-ee7b-4519-b17a-03b45c457a9e HTTP/1.1
Content-Type: application/json
Authorization: r1uh2ra3jc1wnd4e5vds8xaa2gze6f

{
    //"name": "channel 2",
    //"description": "Es un canal de prueba",
    //"project":"proyecto 2021",
    "ubication":{
        "latitude": 2.0,
        "longitude": 1.0
    }
}

//delete channel
###
DELETE http://localhost:8081/api/channels/ch-802c3cba-2cad-4dfd-a206-e19d3702a8be HTTP/1.1
Content-Type: application/json
Authorization: 1jq7lc8yyhhrtg1kwu80s2hto7i4pj
