//get all datas
###
GET http://localhost:8081/api/data?page=1&page_size=5 HTTP/1.1
Content-Type: application/json
Authorization: 68p7nyib281x9youicx9ra810uk4ve


//Get data from a device
###
GET http://localhost:8081/api/data/dv-089f98d5-25f4-4150-ab4e-18be2f098da2?page_size=100 HTTP/1.1
Content-Type: application/json
Authorization: mzk7g6nmig3ug315akon0s2qb81bfc

//Get specific variable datas from a device 
###
GET http://localhost:8081/api/data/dv-089f98d5-25f4-4150-ab4e-18be2f098da2 HTTP/1.1
Content-Type: application/json
Authorization: mzk7g6nmig3ug315akon0s2qb81bfc

//Get specific variable datas from a device with a aggregation operation
###
GET http://localhost:8081/api/data/dv-089f98d5-25f4-4150-ab4e-18be2f098da2/agregate?operation=sum HTTP/1.1
Content-Type: application/json
Authorization: mzk7g6nmig3ug315akon0s2qb81bfc

//Get last data from a device
###
GET http://localhost:8081/api/data/dv-089f98d5-25f4-4150-ab4e-18be2f098da2/last HTTP/1.1
Content-Type: application/json
Authorization: mzk7g6nmig3ug315akon0s2qb81bfc
//68p7nyib281x9youicx9ra810uk4ve

//Export data from a channel
###
GET http://localhost:8081/api/data/ch-32e48add-c489-425e-bd48-fd7ffbd7d8f7/export HTTP/1.1
Content-Type: application/json
Authorization: 68p7nyib281x9youicx9ra810uk4ve