
//Obtener todos los dispositivos
###
GET http://localhost:8081/api/devices?page=1&page_size=4 HTTP/1.1
Content-Type: application/json
Authorization: 68p7nyib281x9youicx9ra810uk4ve



//Crear un dispositivo en un canal
###
POST http://localhost:8081/api/channels/ch-2cf804f3-5290-412f-ace7-8df8bb8e74bb/devices HTTP/1.1
Content-Type: application/json
Authorization: ch032ywc7wbwqwjnkrx23rmfdknb5m

{
    "name":"Sensor de temperatura",
    "description":"Sensor de la estacion meteorologica",
    "model":"DHT22",
    "type":"digital",
    "measures":[
       {
        "variable":"temperature",
        "unit":"C"
       },
         {
          "variable":"humidity",
          "unit":"%"
         }
    ]
}

//Obtener todos los dispositivos de un canal
###
GET http://localhost:8081/api/channels/ch-2cf804f3-5290-412f-ace7-8df8bb8e74bb/devices?page=1 HTTP/1.1
Content-Type: application/json
Authorization: ch032ywc7wbwqwjnkrx23rmfdknb5m


//Obtener un dispositivo de un canal
###
GET http://localhost:8081/api/channels/ch-32e48add-c489-425e-bd48-fd7ffbd7d8f7/devices/dv-089f98d5-25f4-4150-ab4e-18be2f098da2 HTTP/1.1
Content-Type: application/json
Authorization: 68p7nyib281x9youicx9ra810uk4ve

//Actualizar un dispositivo de un canal
###
PUT http://localhost:8081/api/channels/ch-32e48add-c489-425e-bd48-fd7ffbd7d8f7/devices/dv-089f98d5-25f4-4150-ab4e-18be2f098da2 HTTP/1.1
Content-Type: application/json
Authorization: 68p7nyib281x9youicx9ra810uk4ve
 
 {
    "isActive":true
 }

###
DELETE http://localhost:8081/api/channels/ch-2cf804f3-5290-412f-ace7-8df8bb8e74bb/devices/dv-1781932c-f09b-4f25-bd34-3eeaddcbace4 HTTP/1.1
Content-Type: application/json
Authorization: ch032ywc7wbwqwjnkrx23rmfdknb5m


