###
GET http://localhost:8081/api/v1/users HTTP/1.1
Content-Type: application/json
Authorization: 68p7nyib281x9youicx9ra810uk4ve



//get user by id
###
GET http://localhost:8081/api/v1/users/658355548398f5fa3b69e862 HTTP/1.1
Content-Type: application/json
Authorization: 68p7nyib281x9youicx9ra810uk4ve


//create user
###
POST http://localhost:8081/api/v1/users HTTP/1.1
Content-Type: application/json
Authorization: 68p7nyib281x9youicx9ra810uk4ve

{
    "username":"elemejor",
    "name":"Iluminado",
    "lastName":"Amado",
    "email":"iluminado.amado@userena.cl",
    "password":"IluminadoAmado2024!",
    "type":"advancedUser",
    "superuser":false
}


###
PUT http://localhost:8081/api/v1/users/658e3ae9638ee5284cf59247 HTTP/1.1
Content-Type: application/json
Authorization: tefcrh7fsbqjxksqfrlothepz7weq9

{
    "lastName":"RodriguezXD"
}


###
DELETE http://localhost:8081/api/v1/users/655a6e7848cfbb889b2d0363 HTTP/1.1
Content-Type: application/json
Authorization: 68p7nyib281x9youicx9ra810uk4ve
