###
GET http://localhost:8081/api/users HTTP/1.1
Content-Type: application/json
Authorization: r1uh2ra3jc1wnd4e5vds8xaa2gze6f


###
GET http://localhost:8081/api/users/6553086014241c7f7371bd59 HTTP/1.1
Content-Type: application/json
Authorization: r1uh2ra3jc1wnd4e5vds8xaa2gze6f


//create user
###
POST http://localhost:8081/api/users HTTP/1.1
Content-Type: application/json
Authorization: r1uh2ra3jc1wnd4e5vds8xaa2gze6f

{
    "name":"Antony",
    "lastName":"Rodriguez",
    "email":"anton2002y@gmail.com",
    "password":"12345",
    "type":"advancedUser"
}


###
PUT http://localhost:8081/api/users/6553086014241c7f7371bd59 HTTP/1.1
Content-Type: application/json
Authorization: r1uh2ra3jc1wnd4e5vds8xaa2gze6f

{
    "lastName":"Rodriguez"
}


###
DELETE http://localhost:8081/api/users/655a6e7848cfbb889b2d0363 HTTP/1.1
Content-Type: application/json
Authorization: r1uh2ra3jc1wnd4e5vds8xaa2gze6f
